---
version: '3.8'

services:
  mysql:
    image: ghcr.io/isithin/bi-db:demo
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bi_net

  python-app:
    image: ghcr.io/isithin/bi-scraper:demo
    container_name: python_container
    depends_on:
      - mysql
    working_dir: /app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: ["python3", "connector-test.py"]
    networks:
      - bi_net

networks:
  bi_net:
    driver: bridge
