---
version: '3.8'

services:
  mysql:
    image: ghcr.io/isithin/bi-db:demo
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "33306:3306"
    networks:
      - bi_net

  python-app:
    image: ghcr.io/isithin/bi-scraper:demo
    container_name: python_container
    depends_on:
      - mysql
    working_dir: /app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: ["python3", "connector-test.py"]
    networks:
      - bi_net

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=${GF_DATABASE_USER}
      - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
    networks:
      - bi_net

networks:
  bi_net:
    driver: bridge
