---
version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    hostname: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      command: >
        bash -c "sleep 20
        && mysql -u root -p${MYSQL_ROOT_PASSWORD} -P 3306 -h 127.0.0.1 grafana < /mnt/db-backup.sql"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./app/grafana_dumps:/mnt
# for debugging
#    ports:
#      - "33306:3306"
    networks:
      - bi_net

  python-app:
    image: ghcr.io/isithin/bi-scraper:demo
    container_name: python_container
    depends_on:
      - mysql
    working_dir: /app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
    command: >
      bash -c "python3 db_init.py
      && sleep 10
      && python3 /app/webscraping/run_scrapers.py"
    volumes:
      - ./app:/app
    networks:
      - bi_net

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:33000:3000"
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=${GF_DATABASE_USER}
      - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
      - GF_FEATURE_TOGGLES_ENABLE=featureToggleAdminPage, regressionTransformation
      - GF_FEATURE_MANAGEMENT_ALLOW_EDITING=true    
    networks:
      - bi_net

networks:
  bi_net:
    driver: bridge
