FROM python:3.9

RUN pip install --no-cache-dir mysql-connector-python
RUN pip install pandas openpyxl sqlalchemy pymysql requests
RUN apt update && apt -y install mysql-client

ADD app /app

WORKDIR /app

COPY app /app

#CMD ["python3", "db_init.py"]
