FROM python:3.9

# Aktualisieren der Paketliste und Installation von Grafana
RUN apt-get update && apt-get install -y wget gnupg2 && \
    wget -q -O - https://packages.grafana.com/gpg.key | apt-key add - && \
    echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list && \
    apt-get update && apt-get install -y grafana && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Port für Grafana freigeben
EXPOSE 3000

# Startbefehl für Grafana und das Python-Skript
CMD service grafana-server start && tail -f /dev/null
