name: build_and_push

on:
  push:
    branches: ["podman-build"]

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: build and push image
        run: |
          podman login -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman build -t ghcr.io/isithin/bi:demo -f ./app/Dockerfile ./app
          podman push ghcr.io/isithin/bi:demo

  run-mysql:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Create DB Directory
        run: mkdir -p ${{ github.workspace }}/mysql_data
      - name: Run MySQL Container with External Volume
        run: |
          podman run -d \
            --name bi_app \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e MYSQL_DATABASE=bi \
            -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
            -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -v ${{ github.workspace }}/mysql_data:/var/lib/mysql \
            -p 3306:3306 \
            ghcr.io/isithin/bi:demo         
    
      - name: Verify MySQL Container
        run: |
          sleep 10
          podman ps -a
          podman logs bi_app
