name: build_and_push

on:
  push:
    branches: ["podman-build"]

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: build and push mysql image
        run: |
          podman login -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman build -t ghcr.io/isithin/bi-db:demo -f ./app/Dockerfile-mysql .
          podman push ghcr.io/isithin/bi-db:demo        
      - name: build and push scraper image
        run: |
          podman login -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman build -t ghcr.io/isithin/bi-scraper:demo -f ./app/Dockerfile-scraper .
          podman push ghcr.io/isithin/bi-scraper:demo

  test:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run compose
        run: |
          podman-compose up -d
          sleep
          podman logs python_container
          podman logs mysql_container
