name: build_and_push

on:
  push:
    branches: ["podman-build"]

jobs:
  build-push-mage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: build and push image
        run: |
          podman login -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman build -t ghcr.io/${{ github.actor }}/bi:demo -f ./app/Dockerfile ./app
          podman push ghcr.io/isithin/bi:demo
